/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funcionalidades.ConfiguradorDeInterfaz;
import Funcionalidades.ObtenerDatos;
import POJOS.Usuarios;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class MainFrame extends javax.swing.JFrame {

    private SessionFactory factory;
    private ObtenerDatos obtenerDatos;

    // Información servidor socket
    private static final String SERVER_IP = "192.168.1.45";
    private static final int SERVER_PORT = 5000;
    private static final String LOCAL_FOLDER = "EscudosDescargados";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this(0, null);
    }

    public MainFrame(int pkUsuario, String rol) {
        initComponents();
        setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage("src/main/resources/images/logo.png");
        setIconImage(icon);
        // Inicializar factory
        initializeSessionFactory();
        // Crear objeto de obtención de datos
        obtenerDatos = new ObtenerDatos(factory);
        // Rellenar el combox de ligas
        rellenarComboxLigas();

        System.out.println("Cargando datos del usuario...");
        cargarPanelUsuario(pkUsuario);

        System.out.println("Configurando interfaz por rol...");
        if (rol != null) {
            ConfiguradorDeInterfaz.configurarPorRol(rol, this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        appPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        resizableImageLabel1 = new Componentes.ResizableImageLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ligaComboBox = new javax.swing.JComboBox<>();
        resultadosClasifiacionPanel = new javax.swing.JPanel();
        resultadosPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        resultadosButton = new javax.swing.JButton();
        clasificacionResultadosButton = new javax.swing.JButton();
        usuarioResultadosButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jornadaComboBox = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clasificacionPanel = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jToolBar5 = new javax.swing.JToolBar();
        resultadosClasificacionButton = new javax.swing.JButton();
        clasificacionButton = new javax.swing.JButton();
        usuariosClasificacionButton = new javax.swing.JButton();
        userPanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        nombreUsuarioLabel = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rolUsuarioLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        correoUsuarioLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fechaRegistroUsuarioLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idUsuarioLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        equipoFavoritoLabel = new javax.swing.JLabel();
        escudoFavoritoPanel = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        resultadosUsuarioButton = new javax.swing.JButton();
        clasificacionUsuarioButton = new javax.swing.JButton();
        usuarioButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();
        devMenu = new javax.swing.JMenu();
        crearPartidoMenuItem = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        acercaDeMenuItem = new javax.swing.JMenuItem();
        webMenuItem = new javax.swing.JMenuItem();
        ayudaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Befootball");
        setBackground(new java.awt.Color(0, 0, 0));

        mainPanel.setLayout(new java.awt.CardLayout());

        appPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jToolBar1.setBackground(new java.awt.Color(229, 229, 0));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jPanel4.setBackground(new java.awt.Color(229, 229, 0));

        resizableImageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        resizableImageLabel1.setText("resizableImageLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resizableImageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(resizableImageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBar1.add(jPanel4);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jToolBar1.add(jSeparator1);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 69, 193));
        jLabel1.setText("Liga:");
        jToolBar1.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(229, 229, 0));

        ligaComboBox.setBackground(new java.awt.Color(255, 0, 0));
        ligaComboBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ligaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ligaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligaComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ligaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ligaComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.add(jPanel2);

        jPanel1.add(jToolBar1);

        appPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        resultadosClasifiacionPanel.setBackground(new java.awt.Color(0, 0, 0));
        resultadosClasifiacionPanel.setLayout(new java.awt.CardLayout());

        resultadosPanel.setBackground(new java.awt.Color(0, 0, 0));
        resultadosPanel.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jToolBar2.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        resultadosButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        resultadosButton.setForeground(new java.awt.Color(102, 255, 255));
        resultadosButton.setText("Resultados");
        resultadosButton.setContentAreaFilled(false);
        resultadosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultadosButton.setFocusable(false);
        resultadosButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultadosButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(resultadosButton);

        clasificacionResultadosButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clasificacionResultadosButton.setForeground(new java.awt.Color(102, 255, 255));
        clasificacionResultadosButton.setText("Clasificación");
        clasificacionResultadosButton.setContentAreaFilled(false);
        clasificacionResultadosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clasificacionResultadosButton.setFocusable(false);
        clasificacionResultadosButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clasificacionResultadosButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clasificacionResultadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacionResultadosButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(clasificacionResultadosButton);

        usuarioResultadosButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        usuarioResultadosButton.setForeground(new java.awt.Color(102, 255, 255));
        usuarioResultadosButton.setText("Usuario");
        usuarioResultadosButton.setContentAreaFilled(false);
        usuarioResultadosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarioResultadosButton.setFocusable(false);
        usuarioResultadosButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioResultadosButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        usuarioResultadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioResultadosButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(usuarioResultadosButton);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        resultadosPanel.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(229, 229, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jornada");
        jPanel9.add(jLabel2);

        jornadaComboBox.setBackground(new java.awt.Color(229, 229, 0));
        jornadaComboBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jornadaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel9.add(jornadaComboBox);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel11);

        resultadosPanel.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Escudo local", "Equipo local", "Goles local", "Goles visitante", "Equipo visitante", "Escudo visitante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 255, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel12.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        resultadosPanel.add(jPanel12, java.awt.BorderLayout.CENTER);

        resultadosClasifiacionPanel.add(resultadosPanel, "card2");

        clasificacionPanel.setLayout(new java.awt.BorderLayout());

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jPanel22.setBackground(new java.awt.Color(0, 0, 0));
        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.X_AXIS));

        jPanel23.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel23);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(229, 229, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tabla");
        jPanel22.add(jLabel5);

        jComboBox5.setBackground(new java.awt.Color(229, 229, 0));
        jComboBox5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel22.add(jComboBox5);

        jPanel24.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel24);

        jPanel21.add(jPanel22, java.awt.BorderLayout.PAGE_START);

        jPanel25.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel21.add(jPanel25, java.awt.BorderLayout.CENTER);

        jPanel26.setBackground(new java.awt.Color(0, 0, 0));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jToolBar5.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar5.setBorder(null);
        jToolBar5.setFloatable(false);
        jToolBar5.setRollover(true);

        resultadosClasificacionButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        resultadosClasificacionButton.setForeground(new java.awt.Color(102, 255, 255));
        resultadosClasificacionButton.setText("Resultados");
        resultadosClasificacionButton.setContentAreaFilled(false);
        resultadosClasificacionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultadosClasificacionButton.setFocusable(false);
        resultadosClasificacionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultadosClasificacionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resultadosClasificacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosClasificacionButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(resultadosClasificacionButton);

        clasificacionButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clasificacionButton.setForeground(new java.awt.Color(102, 255, 255));
        clasificacionButton.setText("Clasificación");
        clasificacionButton.setContentAreaFilled(false);
        clasificacionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clasificacionButton.setFocusable(false);
        clasificacionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clasificacionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(clasificacionButton);

        usuariosClasificacionButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        usuariosClasificacionButton.setForeground(new java.awt.Color(102, 255, 255));
        usuariosClasificacionButton.setText("Usuario");
        usuariosClasificacionButton.setContentAreaFilled(false);
        usuariosClasificacionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuariosClasificacionButton.setFocusable(false);
        usuariosClasificacionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuariosClasificacionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        usuariosClasificacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosClasificacionButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(usuariosClasificacionButton);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel21.add(jPanel26, java.awt.BorderLayout.PAGE_END);

        clasificacionPanel.add(jPanel21, java.awt.BorderLayout.CENTER);

        resultadosClasifiacionPanel.add(clasificacionPanel, "card3");

        appPanel.add(resultadosClasifiacionPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(appPanel, "card2");

        userPanel.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.X_AXIS));

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel17);

        nombreUsuarioLabel.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        nombreUsuarioLabel.setForeground(new java.awt.Color(229, 229, 0));
        nombreUsuarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuarioLabel.setText("Usuario");
        jPanel16.add(nombreUsuarioLabel);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel18);

        jPanel14.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        jPanel19.setBackground(new java.awt.Color(0, 0, 0));
        jPanel19.setLayout(new java.awt.GridLayout(1, 2));

        jPanel5.setBackground(new java.awt.Color(223, 31, 31));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rol del usuario:");

        rolUsuarioLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rolUsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        rolUsuarioLabel.setText("rol");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo:");

        correoUsuarioLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        correoUsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        correoUsuarioLabel.setText("correo");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Información del usuario");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de registro:");

        fechaRegistroUsuarioLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        fechaRegistroUsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaRegistroUsuarioLabel.setText("fecha");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setText("ID:");

        idUsuarioLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        idUsuarioLabel.setText("id");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idUsuarioLabel))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(correoUsuarioLabel))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rolUsuarioLabel))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaRegistroUsuarioLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rolUsuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(correoUsuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fechaRegistroUsuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(idUsuarioLabel))
                .addContainerGap())
        );

        jPanel19.add(jPanel5);

        jPanel3.setBackground(new java.awt.Color(0, 181, 12));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Equipo favorito");

        equipoFavoritoLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        equipoFavoritoLabel.setForeground(new java.awt.Color(255, 255, 255));
        equipoFavoritoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipoFavoritoLabel.setText("nombre del equipo");

        escudoFavoritoPanel.setBackground(new java.awt.Color(0, 181, 12));

        javax.swing.GroupLayout escudoFavoritoPanelLayout = new javax.swing.GroupLayout(escudoFavoritoPanel);
        escudoFavoritoPanel.setLayout(escudoFavoritoPanelLayout);
        escudoFavoritoPanelLayout.setHorizontalGroup(
            escudoFavoritoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escudoFavoritoPanelLayout.setVerticalGroup(
            escudoFavoritoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escudoFavoritoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(equipoFavoritoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipoFavoritoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escudoFavoritoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel19.add(jPanel3);

        jPanel14.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jToolBar4.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar4.setBorder(null);
        jToolBar4.setFloatable(false);
        jToolBar4.setRollover(true);

        resultadosUsuarioButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        resultadosUsuarioButton.setForeground(new java.awt.Color(102, 255, 255));
        resultadosUsuarioButton.setText("Resultados");
        resultadosUsuarioButton.setContentAreaFilled(false);
        resultadosUsuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultadosUsuarioButton.setFocusable(false);
        resultadosUsuarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultadosUsuarioButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resultadosUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosUsuarioButtonActionPerformed(evt);
            }
        });
        jToolBar4.add(resultadosUsuarioButton);

        clasificacionUsuarioButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clasificacionUsuarioButton.setForeground(new java.awt.Color(102, 255, 255));
        clasificacionUsuarioButton.setText("Clasificación");
        clasificacionUsuarioButton.setContentAreaFilled(false);
        clasificacionUsuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clasificacionUsuarioButton.setFocusable(false);
        clasificacionUsuarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clasificacionUsuarioButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clasificacionUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacionUsuarioButtonActionPerformed(evt);
            }
        });
        jToolBar4.add(clasificacionUsuarioButton);

        usuarioButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        usuarioButton.setForeground(new java.awt.Color(102, 255, 255));
        usuarioButton.setText("Usuario");
        usuarioButton.setContentAreaFilled(false);
        usuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarioButton.setFocusable(false);
        usuarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(usuarioButton);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel14.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        userPanel.add(jPanel14, java.awt.BorderLayout.CENTER);

        mainPanel.add(userPanel, "card2");

        inicioMenu.setText("Inicio");

        logoutMenuItem.setText("Cerrar sesión");
        inicioMenu.add(logoutMenuItem);

        salirMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(salirMenuItem);

        jMenuBar1.add(inicioMenu);

        devMenu.setText("Dev");

        crearPartidoMenuItem.setText("Crear partido");
        crearPartidoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPartidoMenuItemActionPerformed(evt);
            }
        });
        devMenu.add(crearPartidoMenuItem);

        jMenuBar1.add(devMenu);

        ayudaMenu.setText("Ayuda");

        acercaDeMenuItem.setText("Acerca de");
        ayudaMenu.add(acercaDeMenuItem);

        webMenuItem.setText("Página web");
        ayudaMenu.add(webMenuItem);

        ayudaMenuItem.setText("Ayuda");
        ayudaMenu.add(ayudaMenuItem);

        jMenuBar1.add(ayudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioResultadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioResultadosButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelUsuario();
    }//GEN-LAST:event_usuarioResultadosButtonActionPerformed

    private void resultadosUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosUsuarioButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelResultadosUsuario();
    }//GEN-LAST:event_resultadosUsuarioButtonActionPerformed

    private void clasificacionResultadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacionResultadosButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelClasificacion();
    }//GEN-LAST:event_clasificacionResultadosButtonActionPerformed

    private void clasificacionUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacionUsuarioButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelClasificacionUsuario();
    }//GEN-LAST:event_clasificacionUsuarioButtonActionPerformed

    private void resultadosClasificacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosClasificacionButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelResultados();
    }//GEN-LAST:event_resultadosClasificacionButtonActionPerformed

    private void usuariosClasificacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosClasificacionButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelUsuario();
    }//GEN-LAST:event_usuariosClasificacionButtonActionPerformed

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void crearPartidoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPartidoMenuItemActionPerformed
        // TODO add your handling code here:
        CrearPartidoDialog crearPartido = new CrearPartidoDialog(this, rootPaneCheckingEnabled);
        crearPartido.setVisible(true);
    }//GEN-LAST:event_crearPartidoMenuItemActionPerformed

    private void ligaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligaComboBoxActionPerformed
        // TODO add your handling code here:
        // Llamar al método para rellenar el comboBox de jornadas según la liga seleccionada
        String ligaSeleccionada = (String) ligaComboBox.getSelectedItem();

        if (ligaSeleccionada != null) {
            // Limpiar el comboBox de jornadas antes de llenarlo nuevamente
            jornadaComboBox.removeAllItems();
            // Llenar el comboBox con nuevas jornadas
            rellenarComboboxJornadas(ligaSeleccionada);
        }
    }//GEN-LAST:event_ligaComboBoxActionPerformed

    // Crear factorty
    private void initializeSessionFactory() {
        factory = new Configuration().configure().buildSessionFactory();
    }

    // Mostrar panel princiapl
    public void mostrarPanelPrincipal() {
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        // Añadir nombre del panel a cambiar en el panel elegido con cardLayout
        mainPanel.add(appPanel, "appPanel");
        // Mostrar el panel
        cl.show(mainPanel, "appPanel");
    }

    // Mostrar panel de usuario
    public void mostrarPanelUsuario() {
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        // Añadir nombre del panel a cambiar en el panel elegido con cardLayout
        mainPanel.add(userPanel, "userPanel");
        // Mostrar el panel
        cl.show(mainPanel, "userPanel");
    }

    // Mostrar panel de resultados
    public void mostrarPanelResultados() {
        CardLayout cl = (CardLayout) resultadosClasifiacionPanel.getLayout();
        // Añadir nombre del panel a cambiar en el panel elegido con cardLayout
        resultadosClasifiacionPanel.add(resultadosPanel, "resultadosPanel");
        // Mostrar el panel
        cl.show(resultadosClasifiacionPanel, "resultadosPanel");
    }

    // Mostrar panel de clasificación
    public void mostrarPanelClasificacion() {
        CardLayout cl = (CardLayout) resultadosClasifiacionPanel.getLayout();
        // Añadir nombre del panel a cambiar en el panel elegido con cardLayout
        resultadosClasifiacionPanel.add(clasificacionPanel, "clasificacionPanel");
        // Mostrar el panel
        cl.show(resultadosClasifiacionPanel, "clasificacionPanel");
    }

    // Mostrar panel de resultados desde usuario
    public void mostrarPanelResultadosUsuario() {
        mostrarPanelPrincipal();
        mostrarPanelResultados();
    }

    // Mostrar panel de clasificaión desde el panel de usuario
    public void mostrarPanelClasificacionUsuario() {
        mostrarPanelPrincipal();
        mostrarPanelClasificacion();
    }

    // Interfaz para usuario normal
    public void ventanaUsuario() {
        devMenu.setVisible(false);
    }

    // Interfaz para invitado
    public void ventanaInvitado() {
        usuarioButton.setVisible(false);
        usuarioResultadosButton.setVisible(false);
        usuariosClasificacionButton.setVisible(false);
    }

    // Cargar panel de usuario con datos obtenidos comparadno login con la base de datos
    public void cargarPanelUsuario(int pkUsuario) {
        // Crear un objeto de usuario con la información de usuario logueado
        Usuarios usuario = obtenerDatos.obtenerDatosUsuario(pkUsuario);
        // Mostrar nombre del usuario en el label
        nombreUsuarioLabel.setText(usuario.getNombre());
        // Mostrar rol del usuario en el label
        rolUsuarioLabel.setText(usuario.getRol());
        // Mostrar correo del usuario en el label
        correoUsuarioLabel.setText(usuario.getCorreo());
        // Formato para mostrar la fecha y hora de registro del usuario
        DateTimeFormatter formatoDateTime = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        // Mostrar fecha de registro del usuario en el label
        fechaRegistroUsuarioLabel.setText(usuario.getFechaRegistro().format(formatoDateTime));
        // Mostrar id del usuario en el label
        idUsuarioLabel.setText(String.valueOf(pkUsuario));
        // Mostrar nombre del equipo favorito
        equipoFavoritoLabel.setText(usuario.getEquipoFavorito().getNombreEquipo());
        // Cargar escudo favorito
        obtenerEscudoFavorito(pkUsuario);
    }

    // Crear directorio para guardar los escudos en caso de que no exista
    public void crearDirectorioEscudos() {
        File localDir = new File(LOCAL_FOLDER);
        if (!localDir.exists()) {
            localDir.mkdir();
        }
    }

    // Obtener el escudo favorito del usuario
    private void obtenerEscudoFavorito(int pkUsuario) {
        mostrarEscudoEnPanel(obtenerDatos.obtenerDatosUsuario(pkUsuario).getEquipoFavorito().getEscudo(), escudoFavoritoPanel);
    }

    // Descargar el escudo favortio y mostrarlo en el panel
    private void mostrarEscudoEnPanel(String fileName, JPanel panelDestino) {
        File tempFile = new File(LOCAL_FOLDER, fileName);

        // Verificar si la imagen ya está descargada
        if (!tempFile.exists()) {
            try (Socket socket = new Socket(SERVER_IP, SERVER_PORT); PrintWriter writer = new PrintWriter(socket.getOutputStream(), true); InputStream in = socket.getInputStream(); FileOutputStream fileOut = new FileOutputStream(tempFile)) {

                writer.println("DOWNLOAD " + fileName);

                byte[] buffer = new byte[1024];
                int bytesRead;
                while ((bytesRead = in.read(buffer)) != -1) {
                    fileOut.write(buffer, 0, bytesRead);
                }

            } catch (IOException e) {
                System.err.println("Error al descargar el escudo: " + fileName);
                e.printStackTrace();
                return;
            }
        }

        // Cargar la imagen y aplicarla al panel
        ImageIcon icon = new ImageIcon(new ImageIcon(tempFile.getAbsolutePath())
                .getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH));

        JLabel labelEscudo = new JLabel(icon);
        labelEscudo.setHorizontalAlignment(JLabel.CENTER);
        labelEscudo.setVerticalAlignment(JLabel.CENTER);

        // Asegurar que el panel tiene un layout adecuado
        panelDestino.setLayout(new BorderLayout());
        // Limpiar panel antes de agregar la imagen
        panelDestino.removeAll();
        panelDestino.add(labelEscudo, BorderLayout.CENTER);

        // Asegurar que el panel tiene un tamaño adecuado
        panelDestino.setPreferredSize(new Dimension(120, 120));

        panelDestino.revalidate();
        panelDestino.repaint();
    }

    // Rellenar el combox de ligas con los datos obtenidos mediante el objeto obtener datos
    public void rellenarComboxLigas() {
        // Obtener las jornadas de la liga seleccionada
        List<String> nombresLigas = obtenerDatos.obtenerLigas();
        // Llenar el JComboBox con los nombres de las ligas
        for (String nombre : nombresLigas) {
            ligaComboBox.addItem(nombre);
        }
    }

    // Rellenar el combox de jornadas de acuerdo con la liga seleccionada en el comboBox de ligas con los datos obtenidos mediante el objeto obtener datos
    public void rellenarComboboxJornadas(String ligaSeleccionada) {
        List<Integer> numeroJornadas = obtenerDatos.obtenerJornadas(ligaSeleccionada);
        // Llenar el JComboBox con las jornadas
        for (int numero : numeroJornadas) {
            jornadaComboBox.addItem(String.valueOf(numero));
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercaDeMenuItem;
    private javax.swing.JPanel appPanel;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JMenuItem ayudaMenuItem;
    private javax.swing.JButton clasificacionButton;
    private javax.swing.JPanel clasificacionPanel;
    private javax.swing.JButton clasificacionResultadosButton;
    private javax.swing.JButton clasificacionUsuarioButton;
    private javax.swing.JLabel correoUsuarioLabel;
    private javax.swing.JMenuItem crearPartidoMenuItem;
    private javax.swing.JMenu devMenu;
    private javax.swing.JLabel equipoFavoritoLabel;
    private javax.swing.JPanel escudoFavoritoPanel;
    private javax.swing.JLabel fechaRegistroUsuarioLabel;
    private javax.swing.JLabel idUsuarioLabel;
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JComboBox<String> jornadaComboBox;
    private javax.swing.JComboBox<String> ligaComboBox;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nombreUsuarioLabel;
    private Componentes.ResizableImageLabel resizableImageLabel1;
    private javax.swing.JButton resultadosButton;
    private javax.swing.JPanel resultadosClasifiacionPanel;
    private javax.swing.JButton resultadosClasificacionButton;
    private javax.swing.JPanel resultadosPanel;
    private javax.swing.JButton resultadosUsuarioButton;
    private javax.swing.JLabel rolUsuarioLabel;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JPanel userPanel;
    private javax.swing.JButton usuarioButton;
    private javax.swing.JButton usuarioResultadosButton;
    private javax.swing.JButton usuariosClasificacionButton;
    private javax.swing.JMenuItem webMenuItem;
    // End of variables declaration//GEN-END:variables
}
