/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funcionalidades.ConfiguradorDeInterfaz;
import Funcionalidades.ObtenerDatos;
import POJOS.Usuarios;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class MainFrame extends javax.swing.JFrame {

    private SessionFactory factory;
    private ObtenerDatos obtenerDatos;

    // Información servidor socket
    private static final String SERVER_IP = "192.168.1.45";
    private static final int SERVER_PORT = 5000;
    private static final String LOCAL_FOLDER = "EscudosDescargados";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this(0, null);
    }

    public MainFrame(int pkUsuario, String rol) {
        initComponents();
        setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage("src/main/resources/images/logo.png");
        setIconImage(icon);
        // Inicializar factory
        initializeSessionFactory();
        // Crear objeto de obtención de datos
        obtenerDatos = new ObtenerDatos(factory);
        // Rellenar el combox de ligas
        rellenarComboxLigas();

        // Cargar contenido del usuario en caso de haber iniciado sesión
        if (pkUsuario!=0) {
            System.out.println("Cargando datos del usuario...");
            cargarPanelUsuario(pkUsuario);
        }
        
        System.out.println("Configurando interfaz por rol...");
        if (rol != null) {
            ConfiguradorDeInterfaz.configurarPorRol(rol, this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        appPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        resizableImageLabel1 = new Componentes.ResizableImageLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ligaComboBox = new javax.swing.JComboBox<>();
        resultadosClasifiacionPanel = new javax.swing.JPanel();
        resultadosPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        resultadosButton = new javax.swing.JButton();
        clasificacionResultadosButton = new javax.swing.JButton();
        usuarioResultadosButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jornadaComboBox = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clasificacionPanel = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jToolBar5 = new javax.swing.JToolBar();
        resultadosClasificacionButton = new javax.swing.JButton();
        clasificacionButton = new javax.swing.JButton();
        usuariosClasificacionButton = new javax.swing.JButton();
        userPanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        resizableImageLabel2 = new Componentes.ResizableImageLabel();
        nombreUsuarioLabel = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        infoUsuarioPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rolUsuarioLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        correoUsuarioLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fechaRegistroUsuarioLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idUsuarioLabel = new javax.swing.JLabel();
        equipoFavPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        equipoFavoritoLabel = new javax.swing.JLabel();
        escudoFavoritoPanel = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        resultadosUsuarioButton = new javax.swing.JButton();
        clasificacionUsuarioButton = new javax.swing.JButton();
        usuarioButton = new javax.swing.JButton();
        equipoPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        resizableImageLabel3 = new Componentes.ResizableImageLabel();
        jPanel27 = new javax.swing.JPanel();
        nombreEquipoLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ligaEquipoLabel = new javax.swing.JLabel();
        posicionLigaEquipoLabel = new javax.swing.JLabel();
        paisEquipoLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        estadioEquipoLabel = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel29 = new javax.swing.JPanel();
        jToolBar6 = new javax.swing.JToolBar();
        resultadosUsuarioButton1 = new javax.swing.JButton();
        clasificacionUsuarioButton1 = new javax.swing.JButton();
        usuarioButton1 = new javax.swing.JButton();
        partidoPanel = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jToolBar7 = new javax.swing.JToolBar();
        resultadosUsuarioButton2 = new javax.swing.JButton();
        clasificacionUsuarioButton2 = new javax.swing.JButton();
        usuarioButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();
        devMenu = new javax.swing.JMenu();
        crearPartidoMenuItem = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        acercaDeMenuItem = new javax.swing.JMenuItem();
        webMenuItem = new javax.swing.JMenuItem();
        ayudaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Befootball");
        setBackground(new java.awt.Color(0, 0, 0));

        mainPanel.setLayout(new java.awt.CardLayout());

        appPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jToolBar1.setBackground(new java.awt.Color(229, 229, 0));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jPanel4.setBackground(new java.awt.Color(229, 229, 0));

        resizableImageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        resizableImageLabel1.setText("resizableImageLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resizableImageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resizableImageLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
        );

        jToolBar1.add(jPanel4);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jToolBar1.add(jSeparator1);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 69, 193));
        jLabel1.setText("Liga:");
        jToolBar1.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(229, 229, 0));

        ligaComboBox.setBackground(new java.awt.Color(255, 0, 0));
        ligaComboBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ligaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ligaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligaComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ligaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ligaComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.add(jPanel2);

        jPanel1.add(jToolBar1);

        appPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        resultadosClasifiacionPanel.setBackground(new java.awt.Color(0, 0, 0));
        resultadosClasifiacionPanel.setLayout(new java.awt.CardLayout());

        resultadosPanel.setBackground(new java.awt.Color(0, 0, 0));
        resultadosPanel.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jToolBar2.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        resultadosButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        resultadosButton.setForeground(new java.awt.Color(102, 255, 255));
        resultadosButton.setText("Resultados");
        resultadosButton.setContentAreaFilled(false);
        resultadosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultadosButton.setFocusable(false);
        resultadosButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultadosButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(resultadosButton);

        clasificacionResultadosButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clasificacionResultadosButton.setForeground(new java.awt.Color(102, 255, 255));
        clasificacionResultadosButton.setText("Clasificación");
        clasificacionResultadosButton.setContentAreaFilled(false);
        clasificacionResultadosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clasificacionResultadosButton.setFocusable(false);
        clasificacionResultadosButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clasificacionResultadosButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clasificacionResultadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacionResultadosButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(clasificacionResultadosButton);

        usuarioResultadosButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        usuarioResultadosButton.setForeground(new java.awt.Color(102, 255, 255));
        usuarioResultadosButton.setText("Usuario");
        usuarioResultadosButton.setContentAreaFilled(false);
        usuarioResultadosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarioResultadosButton.setFocusable(false);
        usuarioResultadosButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioResultadosButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        usuarioResultadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioResultadosButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(usuarioResultadosButton);

        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        resultadosPanel.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(229, 229, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jornada");
        jPanel9.add(jLabel2);

        jornadaComboBox.setBackground(new java.awt.Color(229, 229, 0));
        jornadaComboBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jornadaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel9.add(jornadaComboBox);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel11);

        resultadosPanel.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Escudo local", "Equipo local", "Goles local", "Goles visitante", "Equipo visitante", "Escudo visitante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 255, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel12.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        resultadosPanel.add(jPanel12, java.awt.BorderLayout.CENTER);

        resultadosClasifiacionPanel.add(resultadosPanel, "card2");

        clasificacionPanel.setLayout(new java.awt.BorderLayout());

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jPanel22.setBackground(new java.awt.Color(0, 0, 0));
        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.X_AXIS));

        jPanel23.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel23);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(229, 229, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tabla");
        jPanel22.add(jLabel5);

        jComboBox5.setBackground(new java.awt.Color(229, 229, 0));
        jComboBox5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel22.add(jComboBox5);

        jPanel24.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel24);

        jPanel21.add(jPanel22, java.awt.BorderLayout.PAGE_START);

        jPanel25.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        jPanel21.add(jPanel25, java.awt.BorderLayout.CENTER);

        jPanel26.setBackground(new java.awt.Color(0, 0, 0));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jToolBar5.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar5.setBorder(null);
        jToolBar5.setFloatable(false);
        jToolBar5.setRollover(true);

        resultadosClasificacionButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        resultadosClasificacionButton.setForeground(new java.awt.Color(102, 255, 255));
        resultadosClasificacionButton.setText("Resultados");
        resultadosClasificacionButton.setContentAreaFilled(false);
        resultadosClasificacionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultadosClasificacionButton.setFocusable(false);
        resultadosClasificacionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultadosClasificacionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resultadosClasificacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosClasificacionButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(resultadosClasificacionButton);

        clasificacionButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clasificacionButton.setForeground(new java.awt.Color(102, 255, 255));
        clasificacionButton.setText("Clasificación");
        clasificacionButton.setContentAreaFilled(false);
        clasificacionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clasificacionButton.setFocusable(false);
        clasificacionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clasificacionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(clasificacionButton);

        usuariosClasificacionButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        usuariosClasificacionButton.setForeground(new java.awt.Color(102, 255, 255));
        usuariosClasificacionButton.setText("Usuario");
        usuariosClasificacionButton.setContentAreaFilled(false);
        usuariosClasificacionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuariosClasificacionButton.setFocusable(false);
        usuariosClasificacionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuariosClasificacionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        usuariosClasificacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosClasificacionButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(usuariosClasificacionButton);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel21.add(jPanel26, java.awt.BorderLayout.PAGE_END);

        clasificacionPanel.add(jPanel21, java.awt.BorderLayout.CENTER);

        resultadosClasifiacionPanel.add(clasificacionPanel, "card3");

        appPanel.add(resultadosClasifiacionPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(appPanel, "card2");

        userPanel.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.X_AXIS));

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        resizableImageLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        resizableImageLabel2.setText("resizableImageLabel1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resizableImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resizableImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel16.add(jPanel17);

        nombreUsuarioLabel.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        nombreUsuarioLabel.setForeground(new java.awt.Color(229, 229, 0));
        nombreUsuarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuarioLabel.setText("Usuario");
        jPanel16.add(nombreUsuarioLabel);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel18);

        jPanel14.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        jPanel19.setBackground(new java.awt.Color(0, 0, 0));
        jPanel19.setLayout(new java.awt.GridLayout(1, 2));

        infoUsuarioPanel.setBackground(new java.awt.Color(223, 31, 31));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rol del usuario:");

        rolUsuarioLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rolUsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        rolUsuarioLabel.setText("rol");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo:");

        correoUsuarioLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        correoUsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        correoUsuarioLabel.setText("correo");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Información del usuario");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de registro:");

        fechaRegistroUsuarioLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        fechaRegistroUsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaRegistroUsuarioLabel.setText("fecha");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setText("ID:");

        idUsuarioLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        idUsuarioLabel.setText("id");

        javax.swing.GroupLayout infoUsuarioPanelLayout = new javax.swing.GroupLayout(infoUsuarioPanel);
        infoUsuarioPanel.setLayout(infoUsuarioPanelLayout);
        infoUsuarioPanelLayout.setHorizontalGroup(
            infoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoUsuarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(infoUsuarioPanelLayout.createSequentialGroup()
                        .addGroup(infoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoUsuarioPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idUsuarioLabel))
                            .addGroup(infoUsuarioPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(correoUsuarioLabel))
                            .addGroup(infoUsuarioPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rolUsuarioLabel))
                            .addGroup(infoUsuarioPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaRegistroUsuarioLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        infoUsuarioPanelLayout.setVerticalGroup(
            infoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoUsuarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(infoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rolUsuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(correoUsuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fechaRegistroUsuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(infoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(idUsuarioLabel))
                .addContainerGap())
        );

        jPanel19.add(infoUsuarioPanel);

        equipoFavPanel.setBackground(new java.awt.Color(0, 181, 12));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Equipo favorito");

        equipoFavoritoLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        equipoFavoritoLabel.setForeground(new java.awt.Color(255, 255, 255));
        equipoFavoritoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipoFavoritoLabel.setText("nombre del equipo");

        escudoFavoritoPanel.setBackground(new java.awt.Color(0, 181, 12));

        javax.swing.GroupLayout escudoFavoritoPanelLayout = new javax.swing.GroupLayout(escudoFavoritoPanel);
        escudoFavoritoPanel.setLayout(escudoFavoritoPanelLayout);
        escudoFavoritoPanelLayout.setHorizontalGroup(
            escudoFavoritoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escudoFavoritoPanelLayout.setVerticalGroup(
            escudoFavoritoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout equipoFavPanelLayout = new javax.swing.GroupLayout(equipoFavPanel);
        equipoFavPanel.setLayout(equipoFavPanelLayout);
        equipoFavPanelLayout.setHorizontalGroup(
            equipoFavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, equipoFavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(equipoFavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escudoFavoritoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(equipoFavoritoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        equipoFavPanelLayout.setVerticalGroup(
            equipoFavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipoFavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipoFavoritoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escudoFavoritoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel19.add(equipoFavPanel);

        jPanel14.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jToolBar4.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar4.setBorder(null);
        jToolBar4.setFloatable(false);
        jToolBar4.setRollover(true);

        resultadosUsuarioButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        resultadosUsuarioButton.setForeground(new java.awt.Color(102, 255, 255));
        resultadosUsuarioButton.setText("Resultados");
        resultadosUsuarioButton.setContentAreaFilled(false);
        resultadosUsuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultadosUsuarioButton.setFocusable(false);
        resultadosUsuarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultadosUsuarioButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resultadosUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosUsuarioButtonActionPerformed(evt);
            }
        });
        jToolBar4.add(resultadosUsuarioButton);

        clasificacionUsuarioButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clasificacionUsuarioButton.setForeground(new java.awt.Color(102, 255, 255));
        clasificacionUsuarioButton.setText("Clasificación");
        clasificacionUsuarioButton.setContentAreaFilled(false);
        clasificacionUsuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clasificacionUsuarioButton.setFocusable(false);
        clasificacionUsuarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clasificacionUsuarioButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clasificacionUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacionUsuarioButtonActionPerformed(evt);
            }
        });
        jToolBar4.add(clasificacionUsuarioButton);

        usuarioButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        usuarioButton.setForeground(new java.awt.Color(102, 255, 255));
        usuarioButton.setText("Usuario");
        usuarioButton.setContentAreaFilled(false);
        usuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarioButton.setFocusable(false);
        usuarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(usuarioButton);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel14.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        userPanel.add(jPanel14, java.awt.BorderLayout.CENTER);

        mainPanel.add(userPanel, "card2");

        equipoPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        jPanel13.setBackground(new java.awt.Color(0, 51, 204));

        jPanel7.setBackground(new java.awt.Color(0, 51, 204));

        resizableImageLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        resizableImageLabel3.setText("resizableImageLabel1");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resizableImageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resizableImageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel13);

        jPanel27.setBackground(new java.awt.Color(0, 51, 204));

        nombreEquipoLabel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        nombreEquipoLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreEquipoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEquipoLabel.setText("Equipo");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreEquipoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreEquipoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel27);

        jPanel5.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);

        equipoPanel.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel20.setLayout(new java.awt.GridLayout(1, 0));

        jPanel28.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Información");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Pais:");

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Liga:");

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Posición en liga:");

        ligaEquipoLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ligaEquipoLabel.setForeground(new java.awt.Color(255, 255, 255));
        ligaEquipoLabel.setText("liga");

        posicionLigaEquipoLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        posicionLigaEquipoLabel.setForeground(new java.awt.Color(255, 255, 255));
        posicionLigaEquipoLabel.setText("pos");

        paisEquipoLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        paisEquipoLabel.setForeground(new java.awt.Color(255, 255, 255));
        paisEquipoLabel.setText("pais");

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Estadio:");

        estadioEquipoLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        estadioEquipoLabel.setForeground(new java.awt.Color(255, 255, 255));
        estadioEquipoLabel.setText("estadio");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paisEquipoLabel))
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ligaEquipoLabel))
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicionLigaEquipoLabel))
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadioEquipoLabel)))
                        .addGap(0, 179, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(paisEquipoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ligaEquipoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(posicionLigaEquipoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(estadioEquipoLabel))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jPanel20.add(jPanel28);

        jPanel30.setBackground(new java.awt.Color(102, 102, 102));
        jPanel30.setLayout(new java.awt.GridLayout(2, 1));

        jPanel31.setBackground(new java.awt.Color(102, 102, 102));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Escudo");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel30.add(jPanel31);

        jPanel32.setBackground(new java.awt.Color(102, 102, 102));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Jugadores");
        jPanel32.add(jLabel11, java.awt.BorderLayout.PAGE_START);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Nacionalidad", "Posición", "Dorsal"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel32.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel30.add(jPanel32);

        jPanel20.add(jPanel30);

        equipoPanel.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel29.setBackground(new java.awt.Color(0, 0, 0));
        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jToolBar6.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar6.setBorder(null);
        jToolBar6.setFloatable(false);
        jToolBar6.setRollover(true);

        resultadosUsuarioButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        resultadosUsuarioButton1.setForeground(new java.awt.Color(102, 255, 255));
        resultadosUsuarioButton1.setText("Resultados");
        resultadosUsuarioButton1.setContentAreaFilled(false);
        resultadosUsuarioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultadosUsuarioButton1.setFocusable(false);
        resultadosUsuarioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultadosUsuarioButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resultadosUsuarioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosUsuarioButton1ActionPerformed(evt);
            }
        });
        jToolBar6.add(resultadosUsuarioButton1);

        clasificacionUsuarioButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clasificacionUsuarioButton1.setForeground(new java.awt.Color(102, 255, 255));
        clasificacionUsuarioButton1.setText("Clasificación");
        clasificacionUsuarioButton1.setContentAreaFilled(false);
        clasificacionUsuarioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clasificacionUsuarioButton1.setFocusable(false);
        clasificacionUsuarioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clasificacionUsuarioButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clasificacionUsuarioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacionUsuarioButton1ActionPerformed(evt);
            }
        });
        jToolBar6.add(clasificacionUsuarioButton1);

        usuarioButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        usuarioButton1.setForeground(new java.awt.Color(102, 255, 255));
        usuarioButton1.setText("Usuario");
        usuarioButton1.setContentAreaFilled(false);
        usuarioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarioButton1.setFocusable(false);
        usuarioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(usuarioButton1);

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar6, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        equipoPanel.add(jPanel29, java.awt.BorderLayout.PAGE_END);

        mainPanel.add(equipoPanel, "card4");

        partidoPanel.setLayout(new java.awt.BorderLayout());

        jPanel34.setBackground(new java.awt.Color(0, 0, 0));
        jPanel34.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel34.add(jPanel37);

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("0");
        jPanel34.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("-");
        jPanel34.add(jLabel17);

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("0");
        jPanel34.add(jLabel18);

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel34.add(jPanel38);

        partidoPanel.add(jPanel34, java.awt.BorderLayout.PAGE_START);

        jPanel35.setBackground(new java.awt.Color(0, 0, 0));

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Estado: X");

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Jornada: X");

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Liga: X");

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Fecha: X");

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        partidoPanel.add(jPanel35, java.awt.BorderLayout.CENTER);

        jPanel36.setBackground(new java.awt.Color(0, 0, 0));
        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jToolBar7.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar7.setBorder(null);
        jToolBar7.setFloatable(false);
        jToolBar7.setRollover(true);

        resultadosUsuarioButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        resultadosUsuarioButton2.setForeground(new java.awt.Color(102, 255, 255));
        resultadosUsuarioButton2.setText("Resultados");
        resultadosUsuarioButton2.setContentAreaFilled(false);
        resultadosUsuarioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultadosUsuarioButton2.setFocusable(false);
        resultadosUsuarioButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultadosUsuarioButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resultadosUsuarioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosUsuarioButton2ActionPerformed(evt);
            }
        });
        jToolBar7.add(resultadosUsuarioButton2);

        clasificacionUsuarioButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clasificacionUsuarioButton2.setForeground(new java.awt.Color(102, 255, 255));
        clasificacionUsuarioButton2.setText("Clasificación");
        clasificacionUsuarioButton2.setContentAreaFilled(false);
        clasificacionUsuarioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clasificacionUsuarioButton2.setFocusable(false);
        clasificacionUsuarioButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clasificacionUsuarioButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clasificacionUsuarioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacionUsuarioButton2ActionPerformed(evt);
            }
        });
        jToolBar7.add(clasificacionUsuarioButton2);

        usuarioButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        usuarioButton2.setForeground(new java.awt.Color(102, 255, 255));
        usuarioButton2.setText("Usuario");
        usuarioButton2.setContentAreaFilled(false);
        usuarioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarioButton2.setFocusable(false);
        usuarioButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar7.add(usuarioButton2);

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar7, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        partidoPanel.add(jPanel36, java.awt.BorderLayout.PAGE_END);

        mainPanel.add(partidoPanel, "card5");

        inicioMenu.setText("Inicio");

        logoutMenuItem.setText("Cerrar sesión");
        inicioMenu.add(logoutMenuItem);

        salirMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(salirMenuItem);

        jMenuBar1.add(inicioMenu);

        devMenu.setText("Dev");

        crearPartidoMenuItem.setText("Crear partido");
        crearPartidoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPartidoMenuItemActionPerformed(evt);
            }
        });
        devMenu.add(crearPartidoMenuItem);

        jMenuBar1.add(devMenu);

        ayudaMenu.setText("Ayuda");

        acercaDeMenuItem.setText("Acerca de");
        ayudaMenu.add(acercaDeMenuItem);

        webMenuItem.setText("Página web");
        ayudaMenu.add(webMenuItem);

        ayudaMenuItem.setText("Ayuda");
        ayudaMenu.add(ayudaMenuItem);

        jMenuBar1.add(ayudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioResultadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioResultadosButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelUsuario();
    }//GEN-LAST:event_usuarioResultadosButtonActionPerformed

    private void resultadosUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosUsuarioButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelResultadosUsuario();
    }//GEN-LAST:event_resultadosUsuarioButtonActionPerformed

    private void clasificacionResultadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacionResultadosButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelClasificacion();
    }//GEN-LAST:event_clasificacionResultadosButtonActionPerformed

    private void clasificacionUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacionUsuarioButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelClasificacionUsuario();
    }//GEN-LAST:event_clasificacionUsuarioButtonActionPerformed

    private void resultadosClasificacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosClasificacionButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelResultados();
    }//GEN-LAST:event_resultadosClasificacionButtonActionPerformed

    private void usuariosClasificacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosClasificacionButtonActionPerformed
        // TODO add your handling code here:
        mostrarPanelUsuario();
    }//GEN-LAST:event_usuariosClasificacionButtonActionPerformed

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void crearPartidoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPartidoMenuItemActionPerformed
        // TODO add your handling code here:
        CrearPartidoDialog crearPartido = new CrearPartidoDialog(this, rootPaneCheckingEnabled);
        crearPartido.setVisible(true);
    }//GEN-LAST:event_crearPartidoMenuItemActionPerformed

    private void ligaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligaComboBoxActionPerformed
        // TODO add your handling code here:
        // Llamar al método para rellenar el comboBox de jornadas según la liga seleccionada
        String ligaSeleccionada = (String) ligaComboBox.getSelectedItem();

        if (ligaSeleccionada != null) {
            // Limpiar el comboBox de jornadas antes de llenarlo nuevamente
            jornadaComboBox.removeAllItems();
            // Llenar el comboBox con nuevas jornadas
            rellenarComboboxJornadas(ligaSeleccionada);
        }
    }//GEN-LAST:event_ligaComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarPanelEquipo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultadosUsuarioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosUsuarioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadosUsuarioButton1ActionPerformed

    private void clasificacionUsuarioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacionUsuarioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasificacionUsuarioButton1ActionPerformed

    private void resultadosUsuarioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosUsuarioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadosUsuarioButton2ActionPerformed

    private void clasificacionUsuarioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacionUsuarioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasificacionUsuarioButton2ActionPerformed

    // Crear factorty
    private void initializeSessionFactory() {
        factory = new Configuration().configure().buildSessionFactory();
    }

    // Mostrar panel princiapl
    public void mostrarPanelPrincipal() {
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        // Añadir nombre del panel a cambiar en el panel elegido con cardLayout
        mainPanel.add(appPanel, "appPanel");
        // Mostrar el panel
        cl.show(mainPanel, "appPanel");
    }

    // Mostrar panel de usuario
    public void mostrarPanelUsuario() {
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        // Añadir nombre del panel a cambiar en el panel elegido con cardLayout
        mainPanel.add(userPanel, "userPanel");
        // Mostrar el panel
        cl.show(mainPanel, "userPanel");
    }

    // Mostrar panel de resultados
    public void mostrarPanelResultados() {
        CardLayout cl = (CardLayout) resultadosClasifiacionPanel.getLayout();
        // Añadir nombre del panel a cambiar en el panel elegido con cardLayout
        resultadosClasifiacionPanel.add(resultadosPanel, "resultadosPanel");
        // Mostrar el panel
        cl.show(resultadosClasifiacionPanel, "resultadosPanel");
    }

    // Mostrar panel de clasificación
    public void mostrarPanelClasificacion() {
        CardLayout cl = (CardLayout) resultadosClasifiacionPanel.getLayout();
        // Añadir nombre del panel a cambiar en el panel elegido con cardLayout
        resultadosClasifiacionPanel.add(clasificacionPanel, "clasificacionPanel");
        // Mostrar el panel
        cl.show(resultadosClasifiacionPanel, "clasificacionPanel");
    }
    
    // Mostrar panel de equipo
    public void mostrarPanelEquipo(){
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        // Añadir nombre del panel a cambiar en el panel elegido con cardLayout
        mainPanel.add(equipoPanel, "equipoPanel");
        // Mostrar el panel
        cl.show(mainPanel, "equipoPanel");
    }

    // Mostrar panel de resultados desde usuario
    public void mostrarPanelResultadosUsuario() {
        mostrarPanelPrincipal();
        mostrarPanelResultados();
    }

    // Mostrar panel de clasificaión desde el panel de usuario
    public void mostrarPanelClasificacionUsuario() {
        mostrarPanelPrincipal();
        mostrarPanelClasificacion();
    }

    // Interfaz para usuario normal
    public void ventanaUsuario() {
        devMenu.setVisible(false);
    }

    // Interfaz para invitado
    public void ventanaInvitado() {
        usuarioButton.setVisible(false);
        usuarioResultadosButton.setVisible(false);
        usuariosClasificacionButton.setVisible(false);
    }

    // Cargar panel de usuario con datos obtenidos comparadno login con la base de datos
    public void cargarPanelUsuario(int pkUsuario) {
        // Crear un objeto de usuario con la información de usuario logueado
        Usuarios usuario = obtenerDatos.obtenerDatosUsuario(pkUsuario);
        // Mostrar nombre del usuario en el label
        nombreUsuarioLabel.setText(usuario.getNombre());
        // Mostrar rol del usuario en el label
        rolUsuarioLabel.setText(usuario.getRol());
        // Mostrar correo del usuario en el label
        correoUsuarioLabel.setText(usuario.getCorreo());
        // Formato para mostrar la fecha y hora de registro del usuario
        DateTimeFormatter formatoDateTime = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        // Mostrar fecha de registro del usuario en el label
        fechaRegistroUsuarioLabel.setText(usuario.getFechaRegistro().format(formatoDateTime));
        // Mostrar id del usuario en el label
        idUsuarioLabel.setText(String.valueOf(pkUsuario));
        // Mostrar nombre del equipo favorito
        equipoFavoritoLabel.setText(usuario.getEquipoFavorito().getNombreEquipo());
        // Cargar escudo favorito
        obtenerEscudoFavorito(pkUsuario);
    }

    // Crear directorio para guardar los escudos en caso de que no exista
    public void crearDirectorioEscudos() {
        File localDir = new File(LOCAL_FOLDER);
        if (!localDir.exists()) {
            localDir.mkdir();
        }
    }

    // Obtener el escudo favorito del usuario
    private void obtenerEscudoFavorito(int pkUsuario) {
        mostrarEscudoEnPanel(obtenerDatos.obtenerDatosUsuario(pkUsuario).getEquipoFavorito().getEscudo(), escudoFavoritoPanel);
    }

    // Descargar el escudo favortio y mostrarlo en el panel
    private void mostrarEscudoEnPanel(String fileName, JPanel panelDestino) {
        File tempFile = new File(LOCAL_FOLDER, fileName);

        // Verificar si la imagen ya está descargada
        if (!tempFile.exists()) {
            try (Socket socket = new Socket(SERVER_IP, SERVER_PORT); PrintWriter writer = new PrintWriter(socket.getOutputStream(), true); InputStream in = socket.getInputStream(); FileOutputStream fileOut = new FileOutputStream(tempFile)) {

                // Enviar comando para descargar la imagen al servidor
                writer.println("DOWNLOAD " + fileName);

                byte[] buffer = new byte[1024];
                int bytesRead;
                while ((bytesRead = in.read(buffer)) != -1) {
                    fileOut.write(buffer, 0, bytesRead);
                }

            } catch (IOException e) {
                System.err.println("Error al descargar el escudo: " + fileName);
                e.printStackTrace();
                return;
            }
        }

        // Cargar la imagen y aplicarla al panel
        ImageIcon icon = new ImageIcon(new ImageIcon(tempFile.getAbsolutePath()).getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH));

        // Crear label para el escudo
        JLabel labelEscudo = new JLabel(icon);
        labelEscudo.setHorizontalAlignment(JLabel.CENTER);
        labelEscudo.setVerticalAlignment(JLabel.CENTER);

        // Asegurar que el panel tiene un layout adecuado
        panelDestino.setLayout(new BorderLayout());
        // Limpiar panel antes de agregar la imagen
        panelDestino.removeAll();
        panelDestino.add(labelEscudo, BorderLayout.CENTER);

        // Asegurar que el panel tiene un tamaño adecuado
        panelDestino.setPreferredSize(new Dimension(120, 120));

        // Aplicar imagen
        panelDestino.revalidate();
        panelDestino.repaint();
    }

    // Rellenar el combox de ligas con los datos obtenidos mediante el objeto obtener datos
    public void rellenarComboxLigas() {
        // Obtener las jornadas de la liga seleccionada
        List<String> nombresLigas = obtenerDatos.obtenerLigas();
        // Llenar el JComboBox con los nombres de las ligas
        for (String nombre : nombresLigas) {
            ligaComboBox.addItem(nombre);
        }
    }

    // Rellenar el combox de jornadas de acuerdo con la liga seleccionada en el comboBox de ligas con los datos obtenidos mediante el objeto obtener datos
    public void rellenarComboboxJornadas(String ligaSeleccionada) {
        List<Integer> numeroJornadas = obtenerDatos.obtenerJornadas(ligaSeleccionada);
        // Llenar el JComboBox con las jornadas
        for (int numero : numeroJornadas) {
            jornadaComboBox.addItem(String.valueOf(numero));
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercaDeMenuItem;
    private javax.swing.JPanel appPanel;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JMenuItem ayudaMenuItem;
    private javax.swing.JButton clasificacionButton;
    private javax.swing.JPanel clasificacionPanel;
    private javax.swing.JButton clasificacionResultadosButton;
    private javax.swing.JButton clasificacionUsuarioButton;
    private javax.swing.JButton clasificacionUsuarioButton1;
    private javax.swing.JButton clasificacionUsuarioButton2;
    private javax.swing.JLabel correoUsuarioLabel;
    private javax.swing.JMenuItem crearPartidoMenuItem;
    private javax.swing.JMenu devMenu;
    private javax.swing.JPanel equipoFavPanel;
    private javax.swing.JLabel equipoFavoritoLabel;
    private javax.swing.JPanel equipoPanel;
    private javax.swing.JPanel escudoFavoritoPanel;
    private javax.swing.JLabel estadioEquipoLabel;
    private javax.swing.JLabel fechaRegistroUsuarioLabel;
    private javax.swing.JLabel idUsuarioLabel;
    private javax.swing.JPanel infoUsuarioPanel;
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JComboBox<String> jornadaComboBox;
    private javax.swing.JComboBox<String> ligaComboBox;
    private javax.swing.JLabel ligaEquipoLabel;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nombreEquipoLabel;
    private javax.swing.JLabel nombreUsuarioLabel;
    private javax.swing.JLabel paisEquipoLabel;
    private javax.swing.JPanel partidoPanel;
    private javax.swing.JLabel posicionLigaEquipoLabel;
    private Componentes.ResizableImageLabel resizableImageLabel1;
    private Componentes.ResizableImageLabel resizableImageLabel2;
    private Componentes.ResizableImageLabel resizableImageLabel3;
    private javax.swing.JButton resultadosButton;
    private javax.swing.JPanel resultadosClasifiacionPanel;
    private javax.swing.JButton resultadosClasificacionButton;
    private javax.swing.JPanel resultadosPanel;
    private javax.swing.JButton resultadosUsuarioButton;
    private javax.swing.JButton resultadosUsuarioButton1;
    private javax.swing.JButton resultadosUsuarioButton2;
    private javax.swing.JLabel rolUsuarioLabel;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JPanel userPanel;
    private javax.swing.JButton usuarioButton;
    private javax.swing.JButton usuarioButton1;
    private javax.swing.JButton usuarioButton2;
    private javax.swing.JButton usuarioResultadosButton;
    private javax.swing.JButton usuariosClasificacionButton;
    private javax.swing.JMenuItem webMenuItem;
    // End of variables declaration//GEN-END:variables
}
